@startuml UseCaseDiagram

left to right direction
skinparam actorStyle awesome

actor "User" as U


package "Price Heatmaps"{
    usecase "Efetuar a pesquisa por um Imóvel." as UC1
    usecase "Visualizar os resultados da pesquisa no mapa com o layer de heatmap." as UC2
    usecase "Atualizar as intensidades dos pontos, de acordo com a área do mapa que está a ser mostrada." as UC3
}

U --> UC1
U --> UC2
U --> UC3
