@startuml UseCaseDiagram

left to right direction
skinparam actorStyle awesome

actor "User" as U


package "Price Heatmaps"{
    usecase "Search for Properties in certain a District, County or Parish" as UC1
    usecase "See the results of the search translated to a Heatmap" as UC2
}

U --> UC1
U --> UC2
